"""
Response formatting module.

Ensures the LLM's response strictly adheres to the requested JSON schema.
"""

import json
from typing import Dict, Any

from utils.logger import setup_logger

logger = setup_logger(__name__)


class ResponseFormatter:
    """
    Parses and validates structured JSON outputs from the LLM.
    """

    @staticmethod
    def parse_json_report(response_text: str) -> Dict[str, Any]:
        """
        Extracts and parses a JSON object from raw LLM text output.

        Args:
            response_text (str): The raw string generated by the LLM.

        Returns:
            Dict[str, Any]: The parsed JSON report.
        """
        # Sometimes the LLM wraps JSON in markdown blocks like ```json ... ```
        cleaned_text = response_text.strip()
        
        if cleaned_text.startswith("```json"):
            cleaned_text = cleaned_text[7:]
        elif cleaned_text.startswith("```"):
            cleaned_text = cleaned_text[3:]
            
        if cleaned_text.endswith("```"):
            cleaned_text = cleaned_text[:-3]
            
        cleaned_text = cleaned_text.strip()

        try:
            parsed_json = json.loads(cleaned_text)
            
            # Validate required keys
            required_keys = {
                "patient_information", "image_summary", "classification",
                "confidence", "gradcam_observation", "clinical_interpretation",
                "recommendation", "disclaimer", "generated_report"
            }
            
            missing_keys = required_keys - parsed_json.keys()
            if missing_keys:
                logger.warning(f"Parsed JSON is missing keys: {missing_keys}")
                # Fill missing keys to satisfy structure requirements
                for key in missing_keys:
                    parsed_json[key] = "Information not available."

            return parsed_json
            
        except json.JSONDecodeError as e:
            logger.error(f"Failed to decode JSON from LLM response: {e}")
            logger.debug(f"Raw response was:\n{response_text}")
            
            # Fallback structure if parsing fails completely
            return {
                "patient_information": "Information not available.",
                "image_summary": "Information not available.",
                "classification": "Error parsing LLM response.",
                "confidence": "Error parsing LLM response.",
                "gradcam_observation": "Information not available.",
                "clinical_interpretation": "Failed to parse structured output.",
                "recommendation": "Consult a medical professional.",
                "disclaimer": "This is an AI-generated fallback due to a parsing error.",
                "generated_report": response_text
            }
