import streamlit as st
import os

def render_heatmap_viewer(heatmap_path: str):
    """
    Renders the Grad-CAM heatmap generated by the backend.
    """
    if heatmap_path and os.path.exists(heatmap_path):
        st.image(heatmap_path, caption="Explainability Visualization (Grad-CAM)", use_column_width=True)
    else:
        st.warning("No explainability visualization available.")
