import streamlit as st
import os
from components.sidebar import render_sidebar

st.set_page_config(page_title="About", page_icon="ℹ️", layout="centered")

# Load CSS
css_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "assets", "styles.css")
if os.path.exists(css_path):
    with open(css_path, "r") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

render_sidebar()

st.title("ℹ️ About MedVision AI")

st.markdown("""
### Project Overview
MedVision AI is a multi-agent artificial intelligence system designed to push the boundaries of automated medical image analysis. It leverages state-of-the-art vision models and large language models (LLMs) to not only predict medical conditions but also explain those predictions visually and textually.

### Technologies Used
- **Frontend:** Streamlit, HTML/CSS
- **Backend:** FastAPI, Python 3.11
- **Computer Vision:** PyTorch, Vision Transformer (ViT), Grad-CAM
- **Language Models:** LangChain, Groq (Llama-3/GPT class models)

### Workflow Summary

#### Pipeline A (Vision & Drafting)
1. **Agent 6 (Classifier):** Analyzes the image using a fine-tuned Vision Transformer. Extracts features and generates a Grad-CAM heatmap to explain its attention.
2. **Agent 7 (Report Generator):** Takes the visual findings, predictions, and confidence scores and drafts a structured medical report.

#### Pipeline B (Quality Audit)
3. **Agent 8 (LLM-as-a-Judge):** Reviews the report generated by Agent 7 against a strict 10-point clinical checklist. It ensures there are no AI hallucinations, formatting errors, or medical inconsistencies. If the report fails the threshold, Agent 8 rewrites it iteratively until it passes.

---

**Author:** [Your Name / Team Name]  
**Version:** 1.0.0
""")
