"""
Agent 3 – Feature Extraction Agent.

Loads preprocessed PyTorch tensors generated by Agent 2, passes them
through a pretrained Vision Transformer backbone, and saves the
resulting deep feature embeddings.

Usage (from the project root)::

    python -m agents.agent3_feature_extraction

Requires Agent 2 to have been run first (``datasets/processed/`` must exist).
"""

import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Ensure the project root is on sys.path
# ---------------------------------------------------------------------------
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from config.model_config import FEATURES_DATASET_DIR, FEATURE_DIM, MODEL_BACKBONE
from config.settings import EXPECTED_CLASS_FOLDERS, PROCESSED_DATASET_DIR, REPORTS_DIR
from models.model_loader import ViTFeatureExtractor
from preprocessing.tensor_conversion import TensorConverter
from utils.file_utils import clear_directory, ensure_directory_exists, get_all_files_recursive
from utils.logger import setup_logger

logger = setup_logger(__name__, log_file="agent3_feature_extraction.log")


class FeatureExtractionAgent:
    """
    Feature Extraction Agent for the medical image analysis pipeline.

    Responsibilities
    ----------------
    1. Validate that the processed dataset (tensors) exists.
    2. Initialise the pre-trained Vision Transformer backbone.
    3. Process every tensor through the ViT to extract embeddings.
    4. Save each feature embedding as a ``.pt`` file in ``datasets/features/``.
    5. Maintain a metadata mapping of the extraction process.
    6. Log a detailed summary and save a JSON report.
    """

    def __init__(self) -> None:
        """Initialise the agent with paths and the feature extractor model."""
        self.processed_dir: Path = PROCESSED_DATASET_DIR
        self.features_dir: Path = FEATURES_DATASET_DIR
        self.reports_dir: Path = REPORTS_DIR
        self.expected_classes: list[str] = EXPECTED_CLASS_FOLDERS

        # Load the pre-trained feature extractor
        self.extractor = ViTFeatureExtractor()
        self.converter = TensorConverter()

        # ── Counters & Metadata ─────────────────────────────────────
        self._total_images: int = 0
        self._successful: int = 0
        self._failed: int = 0
        self._metadata_map: list[dict] = []
        self._failed_files: list[str] = []

    # =====================================================================
    #  Public API
    # =====================================================================

    def run(self) -> dict:
        """
        Execute the feature extraction pipeline on the processed dataset.

        Returns:
            A dictionary containing the extraction report.

        Raises:
            FileNotFoundError: If the processed dataset does not exist.
        """
        start_time = time.time()

        logger.info("=" * 60)
        logger.info("  FEATURE EXTRACTION AGENT – Starting")
        logger.info("=" * 60)
        logger.info(f"Input (processed) : {self.processed_dir}")
        logger.info(f"Output (features) : {self.features_dir}")
        logger.info(f"Model Backbone    : {MODEL_BACKBONE}")

        # Step 1 — Validate input
        self._validate_input()

        # Step 2 — Prepare output directory (fresh start)
        clear_directory(self.features_dir)

        # Step 3 — Extract features
        self._extract_all_features()

        elapsed = time.time() - start_time

        # Step 4 — Generate and save report
        report = self._generate_report(elapsed)
        self._save_report(report)

        # Step 5 — Log summary
        self._log_summary(elapsed)

        logger.info("=" * 60)
        logger.info("  FEATURE EXTRACTION AGENT – Completed Successfully")
        logger.info("=" * 60)

        return report

    # =====================================================================
    #  Private helpers
    # =====================================================================

    def _validate_input(self) -> None:
        """
        Verify that the processed dataset directory and class folders exist.

        Raises:
            FileNotFoundError: If any required directory is missing.
        """
        if not self.processed_dir.exists():
            msg = (
                f"Processed dataset not found: {self.processed_dir}\n"
                f"Run Agent 2 (data preprocessing) first."
            )
            logger.error(msg)
            raise FileNotFoundError(msg)

        for class_folder in self.expected_classes:
            class_path = self.processed_dir / class_folder
            if not class_path.exists():
                msg = (
                    f"Expected class folder not found: {class_path}\n"
                    f"Ensure Agent 2 has produced the processed dataset."
                )
                logger.error(msg)
                raise FileNotFoundError(msg)

        logger.info("Input validation passed.")

    # -----------------------------------------------------------------

    def _extract_all_features(self) -> None:
        """
        Iterate over every class folder, load each processed tensor,
        extract features using ViT, and save the embeddings.
        """
        for class_name in self.expected_classes:
            class_dir = self.processed_dir / class_name
            output_class_dir = self.features_dir / class_name
            ensure_directory_exists(output_class_dir)

            # Only target .pt files
            files = [f for f in get_all_files_recursive(class_dir) if f.suffix == ".pt"]
            logger.info(
                f"Extracting features for class '{class_name}': {len(files)} file(s) …"
            )

            class_count = 0
            for file_path in files:
                self._total_images += 1

                try:
                    # 1. Load the preprocessed tensor
                    img_tensor = self.converter.load_tensor(file_path)

                    # 2. Pass through the feature extractor
                    # Feature shape will be (1, FEATURE_DIM)
                    feature_embedding = self.extractor.extract_features(img_tensor)

                    # Detach from graph and move back to CPU before saving
                    feature_embedding = feature_embedding.detach().cpu()

                    # 3. Save as .pt file in the features directory
                    output_name = file_path.name
                    output_path = output_class_dir / output_name
                    self.converter.save_tensor(feature_embedding, output_path)

                    # 4. Maintain metadata relationship
                    self._metadata_map.append({
                        "image_filename": output_name,
                        "label": class_name,
                        "feature_location": str(output_path.relative_to(self.features_dir))
                    })

                    self._successful += 1
                    class_count += 1
                    
                except Exception as e:
                    logger.error(f"Failed to process {file_path.name}: {e}")
                    self._failed += 1
                    self._failed_files.append(str(file_path.relative_to(self.processed_dir)))

            logger.info(
                f"Class '{class_name}' done: {class_count} feature(s) extracted."
            )

    # -----------------------------------------------------------------

    def _generate_report(self, elapsed_seconds: float) -> dict:
        """Build the feature extraction report dictionary."""
        return {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "input_path": str(self.processed_dir),
            "output_path": str(self.features_dir),
            "execution_time_seconds": round(elapsed_seconds, 2),
            "model_config": {
                "backbone": MODEL_BACKBONE,
                "embedding_dimension": FEATURE_DIM,
            },
            "summary": {
                "total_images": self._total_images,
                "successfully_processed": self._successful,
                "failed": self._failed,
            },
            "failed_files": self._failed_files,
            "metadata_sample": self._metadata_map[:5] if self._metadata_map else []
        }

    # -----------------------------------------------------------------

    def _save_report(self, report: dict) -> None:
        """Persist the extraction report and full metadata as JSON."""
        ensure_directory_exists(self.reports_dir)
        
        # Save the primary summary report
        report_path = self.reports_dir / "feature_extraction_report.json"
        try:
            with open(report_path, "w", encoding="utf-8") as f:
                json.dump(report, f, indent=4, ensure_ascii=False)
            logger.info(f"Feature extraction report saved: {report_path}")
        except Exception as e:
            logger.error(f"Failed to save feature extraction report: {e}")
            raise
            
        # Save the full metadata map explicitly requested by prompt
        metadata_path = self.features_dir / "features_metadata.json"
        try:
            with open(metadata_path, "w", encoding="utf-8") as f:
                json.dump(self._metadata_map, f, indent=4, ensure_ascii=False)
            logger.info(f"Full metadata map saved: {metadata_path}")
        except Exception as e:
            logger.error(f"Failed to save metadata map: {e}")

    # -----------------------------------------------------------------

    def _log_summary(self, elapsed_seconds: float) -> None:
        """Print a human-readable summary of the extraction results."""
        logger.info("-" * 50)
        logger.info("  FEATURE EXTRACTION SUMMARY")
        logger.info("-" * 50)
        logger.info(f"  Total images processed: {self._total_images}")
        logger.info(f"  Successfully extracted: {self._successful}")
        logger.info(f"  Failed extraction     : {self._failed}")
        logger.info(f"  Embedding dimensions  : {FEATURE_DIM}")
        logger.info(f"  Extraction time       : {elapsed_seconds:.2f}s")
        logger.info("-" * 50)


# =========================================================================
#  Entry point
# =========================================================================

if __name__ == "__main__":
    agent = FeatureExtractionAgent()
    agent.run()
