"""
Agent 7 – Medical Report Generation (Pipeline B).

Acts as the Report Generation Agent. Accepts the structured prediction JSON from Agent 6,
invokes an LLM (via Groq/OpenRouter) to generate a structured medical report explaining
the prediction, and saves the final consolidated report.

Usage (from the project root)::

    python -m agents.agent7_report_generation [path_to_prediction_json]

If no JSON is provided, it will attempt to pick the latest `prediction_report.json`
from the outputs/predictions directory.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Ensure the project root is on sys.path
# ---------------------------------------------------------------------------
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from backend.services.report_service import ReportService
from config.model_config import PREDICTIONS_DIR
from utils.file_utils import ensure_directory_exists
from utils.logger import setup_logger

logger = setup_logger(__name__, log_file="agent7_report_generation.log")

# Where the final JSON reports will be saved
REPORTS_DIR = _PROJECT_ROOT / "outputs" / "reports"


class MedicalReportGenerationAgent:
    """
    Agent 7: Generates medical reports based on classification inferences.
    """

    def __init__(self) -> None:
        """Initialise the Agent and load the Report Service."""
        logger.info("Initializing Agent 7: Loading Medical Report Service...")
        self.report_service = ReportService()
        ensure_directory_exists(REPORTS_DIR)

    def generate_report_from_file(self, prediction_json_path: Path) -> None:
        """
        Reads the prediction JSON, triggers the report generation, and saves the output.

        Args:
            prediction_json_path (Path): Path to the JSON output from Agent 6.
        """
        if not prediction_json_path.exists():
            logger.error(f"Prediction file not found: {prediction_json_path}")
            sys.exit(1)

        try:
            with open(prediction_json_path, 'r', encoding='utf-8') as f:
                prediction_data = json.load(f)
        except Exception as e:
            logger.error(f"Failed to read prediction JSON: {e}")
            sys.exit(1)

        logger.info("============================================================")
        logger.info("  MEDICAL REPORT GENERATION AGENT (Agent 7) – Starting")
        logger.info("============================================================")

        # Generate the report
        final_report = self.report_service.generate_report(prediction_data)

        # Generate a unique filename using timestamp and image name
        image_name = Path(final_report.get("image_name", "unknown_image")).stem
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_filename = f"report_{image_name}_{timestamp}.json"
        report_path = REPORTS_DIR / report_filename

        try:
            with open(report_path, 'w', encoding='utf-8') as f:
                json.dump(final_report, f, indent=4)
            logger.info(f"Final medical report saved successfully: {report_path}")
        except Exception as e:
            logger.error(f"Failed to save final report: {e}")
            sys.exit(1)

        logger.info("--------------------------------------------------")
        logger.info("  REPORT GENERATION SUMMARY")
        logger.info("--------------------------------------------------")
        logger.info(f"  Target Image    : {final_report.get('image_name')}")
        logger.info(f"  Classification  : {final_report.get('classification')}")
        logger.info(f"  Report Path     : {report_path}")
        logger.info("--------------------------------------------------")
        logger.info("============================================================")
        logger.info("  MEDICAL REPORT GENERATION AGENT – Completed Successfully")
        logger.info("============================================================")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Agent 7: Medical Report Generation")
    parser.add_argument(
        "prediction_json",
        nargs="?",
        type=str,
        help="Path to the prediction JSON generated by Agent 6. Optional."
    )

    args = parser.parse_args()

    # Determine input JSON path
    if args.prediction_json:
        target_json = Path(args.prediction_json).resolve()
    else:
        logger.info("No prediction JSON provided. Searching for the latest Agent 6 output...")
        default_json = PREDICTIONS_DIR / "prediction_report.json"
        if default_json.exists():
            target_json = default_json
            logger.info(f"Found default prediction report: {target_json}")
        else:
            logger.error(f"Default prediction JSON not found at {default_json}. Please provide a path.")
            sys.exit(1)

    agent = MedicalReportGenerationAgent()
    agent.generate_report_from_file(target_json)
